LibraryApp/Models/Database/Entities/Rental.cs
namespace LibraryApp.Models.Database.Entities
{
    public class Rental
    {
        public int RentalId { get; set; }
        public DateOnly RentalDate { get; set; }
        public DateOnly OriginalReturnDeadline { get; set; }
        public DateOnly CurrentDeadline { get; set; }
        public DateOnly? ReturnDate { get; set; }


        //relations
        public string ReaderId { get; set; }
        public Reader Reader { get; set; }

        public int BookCopyId { get; set; }
        public BookCopy BookCopy { get; set; }

        public IList<Renewal> Renewals { get; set; }
    }
}

LibraryApp/Models/Repositories/Rentals/IRentalRepository.cs
using LibraryApp.Models.Database.Entities;

namespace LibraryApp.Models.Repositories.Rentals
{
    public interface IRentalRepository
    {
        Rental? GetRentalById(int id);
        List<Rental> GetReaderRentals(string readerId);
    }
}

LibraryApp/Models/Repositories/Rentals/RentalRepository.cs
using LibraryApp.Models.Database;
using LibraryApp.Models.Database.Entities;
using Microsoft.EntityFrameworkCore;

namespace LibraryApp.Models.Repositories.Rentals
{
    public class RentalRepository : IRentalRepository
    {
        private readonly LibraryDbContext _context;

        public RentalRepository(LibraryDbContext context)
        {
            _context = context;
        }
        public List<Rental> GetReaderRentals(string readerId)
        {
            return _context.Rentals
                .Include(r => r.BookCopy)
                    .ThenInclude(bc => bc.Book)
                .Where(r => r.ReaderId.Equals(readerId)).ToList();
        }

        public Rental? GetRentalById(int id)
        {
            return _context.Rentals
                .Include(r => r.Reader)
                    .ThenInclude(r => r.Penalties)
                        .ThenInclude(p => p.Payment)
                .Include(r => r.Reader)
                .Include(r => r.BookCopy)
                    .ThenInclude(bc => bc.Book)
                .Include(r => r.Renewals)
                .FirstOrDefault(r => r.RentalId == id);
        }
    }
}

LibraryApp/Controllers/RenewalController.cs
using LibraryApp.Models.Renewals.Contracts;
using LibraryApp.Models.Renewals.RenewalErrors;
using LibraryApp.Models.Repositories.Renewals.Contracts;
using LibraryApp.Models.Repositories.Rentals;
using LibraryApp.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LibraryApp.Controllers
{
    [Authorize(Policy = "IsReader")]
    public class RenewalController : Controller
    {
        private readonly IRenewalRepository _renewalRepository;
        private readonly IRentalRepository _rentalRepository;

        public RenewalController(
            IRenewalRepository renewalRepository,
            IRentalRepository rentalRepository)
        {
            _renewalRepository = renewalRepository;
            _rentalRepository = rentalRepository;
        }
        public IActionResult Index(int rentalId)
        {
            var rental = _rentalRepository.GetRentalById(rentalId);
            if (rental == null)
                return NotFound();
            else
            {
                var viewModel = new ConfirmRenewalViewModel()
                {
                    Rental = rental,
                    RemainingRenewals = _renewalRepository.GetRemainingRenewals(rental),
                    RenewalSpanInDays = _renewalRepository.GetRenewalSpan()
                };
                return View(viewModel);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Renew(int rentalId)
        {
            var rental = _rentalRepository.GetRentalById(rentalId);
            if (rental == null) return NotFound();

            var validityCheck = _renewalRepository.IsValidForRenewal(rental);
            if (validityCheck.IsValidForRenewal)
            {
                await _renewalRepository.RenewRental(rentalId);
                return RedirectToAction(nameof(Success), new { rentalId });
            }
            else return DisplayViewForErrors(validityCheck.Errors);
        }

        private ActionResult DisplayViewForErrors(List<RenewalError> errors)
        {
            if (!errors.Any())
                return NotFound();

            var error = errors.First();
            string? viewName = error switch
            {
                _ when error is HasUnpaidPenaltiesError => nameof(UnpaidPenalties),
                _ when error is RenewalsLimitReachedError => nameof(RenewalsLimit),
                _ => null
            };

            return viewName == null ? NotFound() : RedirectToAction(viewName);
        }

        public IActionResult Success(int rentalId)
        {
            var rental = _rentalRepository.GetRentalById(rentalId);
            return rental == null ? NotFound() : View(rental);
        }

        public IActionResult UnpaidPenalties() => View();
        public IActionResult RenewalsLimit() => View();

    }
}

LibraryApp/Controllers/RentalsController.cs
using LibraryApp.Models.Repositories.Readers;
using LibraryApp.Models.Repositories.Rentals;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LibraryApp.Controllers
{
    [Authorize(Policy = "IsReader")]
    public class RentalsController : Controller
    {
        private readonly IReaderRepository _readersRepository;
        private readonly IRentalRepository _rentalRepository;

        public RentalsController(IReaderRepository readersRepository, IRentalRepository rentalRepository)
        {
            _readersRepository = readersRepository;
            _rentalRepository = rentalRepository;
        }

        public async Task<IActionResult> Index()
        {
            var reader = await _readersRepository.GetReaderByUsername(User.Identity?.Name);
            var rentals = (reader == null) ? [] : _rentalRepository.GetReaderRentals(reader.LibraryUserId);
            return View(rentals);
        }
    }
}

LibraryApp/Views/Rentals/Index.cshtml
@model IEnumerable<LibraryApp.Models.Database.Entities.Rental>
@{

}

@section styles {
    <link rel="Stylesheet" href="~/css/rentals-styling-fv2.css" />
}

@if (Model.Any())
{
    <div class="row justify-content-center">
        <div class="col-lg-8">
            @foreach (var rental in Model)
            {
                <div class="card mb-3">
                  <div class="row no-gutters">
                    <div class="col-lg-8 col-md-4">
                      <div class="card-body">
                        <h5 class="card-title">@rental.BookCopy.Book.Title</h5>
                        <p class="card-text author-text">@rental.BookCopy.Book.Author</p>
                        <p class="card-text deadline-text">Return deadline: @rental.CurrentDeadline</p>
                      </div>
                    </div>
                        <div class="col-lg-4 col-md-4">
                            <div class="rental-buttons">
                                <button class="details-button">Details</button>
                                <form method="get" asp-controller="Renewal" asp-action="Index">
                                    <input name="rentalId" value="@rental.RentalId" hidden />
                                    <button class="renew-button" type="submit">Renew</button>
                                </form>
                            </div>
                        </div>
                  </div>
                </div>
            }
        </div>
    </div>
} else
{
    <div class="no-rentals-info-div d-flex flex-column justify-content-center align-items-center" style="height: 75vh">
        <h2 class="text-center">You don't have any rentals</h2>
    </div>
}